name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    #if: false
    runs-on: ${{ matrix.os }}
    
    env:
      DBHOST: localhost
      DBPORT: 5432
      DBUSER: root
      DBPASSWORD: root
      DBNAME: root
    
    strategy:
      matrix:
        go_version: ['1.18']
        os: ['ubuntu-latest']
        #go_version: ['1.18', '1.17', '>=1.18']
        #os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Build-DB
      run: docker compose build
      
    - name: Create-DB
      run: docker compose up -d

    - name: Test
      run: go test -v main_test.go
      
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        #os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go

    - name: Create file Artifact
      env:
        REF_NAME: "${{ vars.GITHUB_REF_NAME }}"
        RUN_NUMBER: "{{ vars.GITHUB_RUN_NUMBER }}"
      run: |
        pwd
        echo $REF_NAME:$RUN_NUMBER
        echo "$REF_NAME:$RUN_NUMBER" > ${{ GITHUB.WORKSPACE }}/version.txt
        #echo "${{ env.GITHUB_REF_NAME }}:${{ env.GITHUB_RUN_NUMBER }}" > version.txt
        #echo "${{ env.REF_NAME }}:${{ env.RUN_NUMBER }}" > version.txt
        ls -lhrt
        cat version.txt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: package
        path: version.txt

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit


