name: Explorer

on:
  workflow_dispatch:

jobs:

  Explorer:
    runs-on: ubuntu-latest
    #environment: dev

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Checkout segundo repo
      uses: actions/checkout@v4.2.2
      with:
        repository: Joejeff/rotten-potatoes
        #ref: main
        path: rotten-potatoes
        

    - name: Echo ENVs  
      run: |
        #env
        #pwd
        #id
        ls -lhart
